### ISSUE TITLE
@JMS\Serializer\Annotation\XmlElement" in property Zeevin\Libiocm\Dm\RequestAttribute\Devices\QueryDevices\Request::$appId does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by GeorgeXiaojie** [zeevin/libiocm#1]
请问，出现这个中问题，是什么原因呢？是我有什么地方没有配置好吗？

**Comment by zeevin** [comment]
1、是否把tests/config.php.sample.php改名为：config.php
2、config.php文件是否配置了正确的appid和secret

**Comment by GeorgeXiaojie** [comment]
确认了一下，配置是没有问题的。

**Comment by zeevin** [comment]
方便的话进QQ群沟通：577640752

**Comment by GeorgeXiaojie** [comment]
已添加您qq

**Comment by zeevin** [comment]
577640752是qq群号，麻烦进群

**Comment by GeorgeXiaojie** [comment]
问题已解决，没有注意作者强调的内容，如下，简单之后需要调用AnnotationRegistry::registerLoader([$loader, 'loadClass']);进行注册。

> 添加一个自定义的autoload.php文件，自己的程序调动的时候引用此autoload.php,不要直接引用vendor/autoload.php内容
